version: '3.8'

services:
  music-backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./music:/app/music
      - music_data:/app/music
    environment:
      - PORT=8080
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  music_data: